refactor: introduce `helpers.sh` for all actions: - All actions now comes bundled with a `helpers.sh` script. This is loaded in all bash script action steps.   - The `helpers.sh` files are identical and only contain common bash functions across all actions.   - The `helpers.sh` script looks for an a file called `helpers_additional.sh` in the same directory as `helpers.sh`. If found this file is sourced at the end of sourcing `helpers.sh`. - All actions have been refactored to utilize common functions like `log-info`, `log-error`, `set-output`, `set-multiline-output` etc.

diff --git a/get-github-app-installation-token/action.yml b/get-github-app-installation-token/action.yml
--- a/get-github-app-installation-token/action.yml
+++ b/get-github-app-installation-token/action.yml
@@ -33,11 +33,12 @@ runs:
   steps:
     - id: get-token
       shell: bash
+      env:
+        GH_APP_KEY: "${{ inputs.github-app-private-key }}"
       run: |
-        # Auth as GiHub App and retreive GitHub App installation access token.
+        # Auth as GitHub App and retrieve GitHub App installation access token.
 
-        # Helper functions
-        function log-info { echo "get-github-app-installation-token: $*"; }
+        set -o allexport; source "${{ github.action_path }}/helpers.sh"; set +o allexport;
 
         log-info "Minting JWT ..."
         JWT_HEADER=$(jq -c -r . <<<"{\"alg\": \"RS256\", \"typ\": \"JWT\"}")
@@ -58,10 +59,8 @@ runs:
             -d '${{ inputs.token-request-body }}'
         )
 
-        # echo "DEBUG: get-github-app-installation-token: exit code: $?"
-        # echo "DEBUG: get-github-app-installation-token: response | jq: $(echo "${GH_APP_TOKEN_RESPONSE}" | jq)"
+        # log-debug "exit code: $?"
+        # log-debug "response | jq: $(echo "${GH_APP_TOKEN_RESPONSE}" | jq)"
 
         log-info "Returning the installation access token ..."
-        echo "github-token=$(echo "${GH_APP_TOKEN_RESPONSE}" | jq -r '.token')" >> $GITHUB_OUTPUT
-      env:
-        GH_APP_KEY: "${{ inputs.github-app-private-key }}"
+        set-output 'github-token' "$(echo "${GH_APP_TOKEN_RESPONSE}" | jq -r '.token')"
