Improvement: maven-build-project: deploy artifacts - Action maven-build-project: Support maven build artifact deploy:   - Will deploy maven snapshot artifacts when running on PR and `maven-build-project-deploy-snapshot-artifacts` is true.   - Will deploy maven release artifacts when running from default branch (push or manually triggered) and `maven-build-project-deploy-release-artifacts` is true.   - Requires `distributionManagement` configuration in project pom.xml. - Action build-spring-boot-image: Make sure build-maven-project action does not attempt to deploy maven artifacts when invoked from this action.

diff --git a/ci-cd/build-maven-project/action.yml b/ci-cd/build-maven-project/action.yml
--- a/ci-cd/build-maven-project/action.yml
+++ b/ci-cd/build-maven-project/action.yml
@@ -34,6 +34,17 @@ description: |
           Otherwise default argument will be used: '-B'.
         - The pom file used will be the one defined by 'application-source-path' in 'dsb-build-envs', can point either to an existing pom.xml or to a directory containing it.
         - The resulting maven invocation command is: mvn <arguments> --file <pom file> <goals>
+  Deploy of build artifacts:
+    - Configure repos in the pom.xml and set one ore both of the following to 'true':
+      - 'maven-build-project-deploy-release-artifacts'
+        - Will deploy artifacts with 'mvn deploy -DskipTests'
+        - To the maven repo configured under <distributionManagement><repository>
+        - Will only deploy artifacts when building from default branch of repo (normally main).
+      - 'maven-build-project-deploy-snapshot-artifacts'
+        - Will invoke 'mvn versions:set -DnewVersion=<version>-SNAPSHOT'
+        - Will deploy artifacts with 'mvn deploy -DskipTests'
+        - To the maven repo configured under <distributionManagement><snapshotRepository>
+        - Will only deploy artifacts when building from PR.
 author: 'Peder Schmedling'
 inputs:
   mvn-version-cmd:
@@ -60,6 +71,8 @@ inputs:
         maven-build-project-command
         maven-build-project-goals
         maven-build-project-arguments
+        maven-build-project-deploy-release-artifacts
+        maven-build-project-deploy-snapshot-artifacts
     required: true
 
 runs:
@@ -80,6 +93,8 @@ runs:
           sonarqube-token
           maven-repo-token
           maven-repo-username
+          caller-repo-calling-branch
+          caller-repo-is-on-default-branch
 
     # locate pom.xml and define maven commands
     - id: mvn-cmd
@@ -209,5 +224,90 @@ runs:
         JASYPT_LOCAL_ENCRYPTOR_PASSWORD: ${{ fromJSON(inputs.dsb-build-envs).jasypt-password }}
         GITHUB_TOKEN: ${{ fromJSON(inputs.dsb-build-envs).github-repo-token }} # Needed for Sonar to get PR information, if any
         SONAR_TOKEN: ${{ fromJSON(inputs.dsb-build-envs).sonarqube-token }}
+        DSB_MAVEN_REPO_TOKEN: ${{ fromJSON(inputs.dsb-build-envs).maven-repo-token }}
+        DSB_MAVEN_REPO_USER_NAME: ${{ fromJSON(inputs.dsb-build-envs).maven-repo-username }}
+
+    # deploy maven build artifacts
+    - shell: bash
+      run: |
+        # Use maven to deploy artifacts when allowed and requested
+
+        BUILD_ENVS=$(cat <<'EOF'
+        ${{ inputs.dsb-build-envs }}
+        EOF
+        )
+
+        # Helper functions
+        # Get field value from BUILD_ENVS safely
+        function get-val { echo "${BUILD_ENVS}" | jq -r --arg name "$1" '.[$name]'; }
+
+        # Locate pom.xml
+        POM_FILE="${{ fromJSON(inputs.dsb-build-envs).application-source-path }}"
+        [ ! -f "${POM_FILE}" ] && POM_FILE="${{ fromJSON(inputs.dsb-build-envs).application-source-path }}/pom.xml"
+        [ ! -f "${POM_FILE}" ] && \
+          echo "ERROR: build-dsb-maven-project: Deploy artifacts: Cannot find pom.xml. Both '${{ fromJSON(inputs.dsb-build-envs).application-source-path }}' and '${POM_FILE}' does not exist!" && \
+          exit 1
+
+        # Determine if we are deploying and with what commands
+        if [ '${{ github.event_name }}' == 'pull_request' ]; then
+          if [ '${{ github.event.action }}' == 'closed' ]; then
+            echo "build-dsb-maven-project: Deploy artifacts: Maven snapshot artifacts will not be deployed when closing PR."
+            exit 0
+          elif [ ! "$(get-val 'maven-build-project-deploy-snapshot-artifacts')" == 'true' ]; then
+            echo "build-dsb-maven-project: Deploy artifacts: Deployment of maven snapshot artifacts not requested."
+            exit 0
+          else
+            echo "build-dsb-maven-project: Deploy artifacts: Will deploy maven snapshot artifacts as requested."
+            MVN_VERSION_CMD="mvn -B --file ${POM_FILE} versions:set -DnewVersion=pr-${{ github.event.number }}-SNAPSHOT"
+            MVN_CMD="mvn -B --file ${POM_FILE} deploy -DskipTests"
+          fi
+        elif [ '${{ github.event_name }}' == 'push' ] || [ '${{ github.event_name }}' == 'workflow_dispatch' ]; then
+          if [ ! '${{ fromJSON(inputs.dsb-build-envs).caller-repo-is-on-default-branch }}' == 'true' ]; then
+            echo "build-dsb-maven-project: Deploy artifacts: Maven release artifacts will not be deployed as current branch '${{ fromJSON(inputs.dsb-build-envs).caller-repo-calling-branch }}' is not the default of this repo."
+            exit 0
+          elif [ ! "$(get-val 'maven-build-project-deploy-release-artifacts')" == 'true' ]; then
+            echo "build-dsb-maven-project: Deploy artifacts: Deployment of maven release artifacts not requested."
+            exit 0
+          else
+            echo "build-dsb-maven-project: Deploy artifacts: Will deploy maven release artifacts as requested."
+            # Version is already set corretly in build step
+            MVN_VERSION_CMD=
+            MVN_CMD="mvn -B --file ${POM_FILE} deploy -DskipTests"
+          fi
+        else
+          echo "ERROR: build-dsb-maven-project: Deploy artifacts: unsupported github.event_name '${{ github.event_name }}' with github.event.action '${{ github.event.action }}'!"
+          exit 1
+        fi
+
+        # Load extra envs if any
+        EXTRA_ENVS=$(cat <<'EOF'
+        ${{ inputs.set-extra-envs }}
+        EOF
+        )
+        if [ ! -z "$EXTRA_ENVS" ]; then
+          echo "::group::build-dsb-maven-project: Deploy artifacts: extra environment variables"
+          JSON_FIELDS=$(echo ${EXTRA_ENVS} | jq -r '[keys[]] | join(" ")')
+          for JSON_FIELD in ${JSON_FIELDS}; do
+              JSON_VALUE=$(echo ${EXTRA_ENVS} | jq -r ".${JSON_FIELD}")
+              echo "Setting extra environment variable '${JSON_FIELD}'"
+              export "${JSON_FIELD}"="${JSON_VALUE}"
+          done
+          echo "::endgroup::"
+        fi
+
+        if [ -z "${MVN_VERSION_CMD}" ]; then
+          echo "build-dsb-maven-project: Deploy artifacts: Project version already set by maven."
+        else
+          echo "::group::build-dsb-maven-project: Setting maven project version for deployment of artifacts"
+          echo "build-dsb-maven-project: Deploy artifacts: command string: '${MVN_VERSION_CMD}'"
+          ${MVN_VERSION_CMD}
+          echo "::endgroup::"
+        fi
+
+        echo "::group::build-dsb-maven-project: Deploy artifacts: Invoke maven"
+        echo "build-dsb-maven-project: Deploy artifacts: command string: '${MVN_CMD}'"
+        ${MVN_CMD}
+        echo "::endgroup::"
+      env:
         DSB_MAVEN_REPO_TOKEN: ${{ fromJSON(inputs.dsb-build-envs).maven-repo-token }}
         DSB_MAVEN_REPO_USER_NAME: ${{ fromJSON(inputs.dsb-build-envs).maven-repo-username }}
