Improvement: maven actions: override invocations: - Action `build-maven-project`:   - Added the possibility to override the maven invocations with inputs `mvn-version-cmd` and `mvn-cmd`.   - Added the possibility to override the maven invocations with inputs `dsb-build-envs.maven-build-project-version-command` and `dsb-build-envs.maven-build-project-command`.   - Added the possibility to override the maven arguments with the inputs `dsb-build-envs.maven-build-project-version-arguments` and `dsb-build-envs.maven-build-project-arguments`.   - Added the possibility to override the maven goals with the inputs `dsb-build-envs.maven-build-project-version-goals` and `dsb-build-envs.maven-build-project-goals`.   - Removed support for inputs `mvn-goals` and `mvn-args`. - Action `build-spring-boot-image`:   - Added the possibility to override the maven invocations with inputs `dsb-build-envs.spring-boot-build-image-version-command` and `dsb-build-envs.spring-boot-build-image-command`.   - Added the possibility to override the maven arguments with the inputs `dsb-build-envs.spring-boot-build-image-version-arguments` and `dsb-build-envs.spring-boot-build-image-arguments`.   - Added the possibility to override the maven goals with the inputs `dsb-build-envs.spring-boot-build-image-version-goals` and `dsb-build-envs.spring-boot-build-image-goals`.   - Removed support for inputs `mvn-goals` and `mvn-args`.

diff --git a/ci-cd/delete-pr-images-from-acr/action.yml b/ci-cd/delete-pr-images-from-acr/action.yml
--- a/ci-cd/delete-pr-images-from-acr/action.yml
+++ b/ci-cd/delete-pr-images-from-acr/action.yml
@@ -4,20 +4,16 @@ description: |
 author: 'Peder Schmedling'
 inputs:
   dsb-build-envs:
-    description: 'DSB build environment variables JSON.'
+    description: |
+      DSB build environment variables JSON.
+      Required fields:
+        See first step.
+      Optional fields:
+        None.
     required: true
 runs:
   using: 'composite'
   steps:
-    - shell: bash
-      run: |
-        # Check if triggered by pull request event
-        [ ! '${{ github.event_name }}' == 'pull_request' ] \
-          && echo 'ERROR: delete-pr-images-from-acr: This action should only be called by pull request events.' \
-          && EXIT_CODE=1 \
-          || EXIT_CODE=0
-        exit ${EXIT_CODE}
-
     # we need to verify inputs since they are optional input to create-build-envs action
     - uses: dsb-norge/github-actions/ci-cd/require-build-envs@v1
       with:
@@ -27,6 +23,15 @@ runs:
           docker-image-registry
           docker-image-repo
           application-image-name
+
+    - shell: bash
+      run: |
+        # Check if triggered by pull request event
+        [ ! '${{ github.event_name }}' == 'pull_request' ] \
+          && echo 'ERROR: delete-pr-images-from-acr: This action should only be called by pull request events.' \
+          && EXIT_CODE=1 \
+          || EXIT_CODE=0
+        exit ${EXIT_CODE}
 
     # log into Azure CLI with service principal
     - uses: azure/login@v1
