Fix: action: deploy-multiple-to-static: Remove local repo dir when done.

diff --git a/ci-cd/deploy-multiple-to-static/action.yml b/ci-cd/deploy-multiple-to-static/action.yml
--- a/ci-cd/deploy-multiple-to-static/action.yml
+++ b/ci-cd/deploy-multiple-to-static/action.yml
@@ -181,9 +181,10 @@ runs:
               git -C "${REPO_DIR}" add "${VALUES_FILE}"
             done # envs
 
-          done # apps
+          done # Loop apps
 
           # Create commit message
+          echo "deploy-multiple-to-static: Creating commit message for repo '${REPO}' ..."
           APPS_IN_REPO_STRING="$(echo "${APPS_IN_REPO_JSON_ARRAY}" | jq -r '. | map( ."application-name" ) | join(", ")')"
           VERSIONS_IN_REPO_STRING="$(echo "${APPS_IN_REPO_JSON_ARRAY}" | jq -r 'unique_by( ."application-version" ) | . | map( ."application-version" ) | join(", ")')"
           BUMP_COMMIT_MESSAGE="🆕 ${INPUT_ENVS_STRING}: ${CALLER_REPO} → ${VERSIONS_IN_REPO_STRING}:"
@@ -194,9 +195,16 @@ runs:
           BUMP_COMMIT_MESSAGE=$(echo "${BUMP_COMMIT_MESSAGE}" $'\n' "Commit message: ${CALLER_REPO_CURRENT_COMMIT_MESSAGE}")
 
           # Git operations
+          echo "deploy-multiple-to-static: Committing version changes for repo '${REPO}' ..."
           git -C "${REPO_DIR}" config user.email "noreply@dsb.no"
           git -C "${REPO_DIR}" config user.name "Auto Bumper"
           git -C "${REPO_DIR}" commit -m "$BUMP_COMMIT_MESSAGE"
           git -C "${REPO_DIR}" push
 
-        done # repos
+          # Cleanup
+          echo "deploy-multiple-to-static: Cleanup: removing '${REPO_DIR}' ..."
+          rm -rf "${REPO_DIR}" \
+            && echo "deploy-multiple-to-static: Cleanup: Done." \
+            || echo "ERROR: deploy-multiple-to-static: Cleanup: Failed to remove repo directory!"
+
+        done # Loop repos
