Improvement: teardown-pr-environment action: More information on error.

diff --git a/ci-cd/teardown-pr-environment/action.yml b/ci-cd/teardown-pr-environment/action.yml
--- a/ci-cd/teardown-pr-environment/action.yml
+++ b/ci-cd/teardown-pr-environment/action.yml
@@ -44,14 +44,52 @@ runs:
         resource-group: ${{ fromJSON(inputs.dsb-build-envs).pr-deploy-aks-resource-group }}
 
     - shell: bash
+      id: helm-uninstall
       run: |
         # Remove helm deployment
 
-        helm uninstall ${{ fromJSON(inputs.dsb-build-envs).pr-deploy-k8s-application-name }} \
-          --namespace ${{ fromJSON(inputs.dsb-build-envs).pr-deploy-k8s-namespace }}
+        if helm uninstall ${{ fromJSON(inputs.dsb-build-envs).pr-deploy-k8s-application-name }} \
+          --namespace ${{ fromJSON(inputs.dsb-build-envs).pr-deploy-k8s-namespace }}; then
+          RESULT='true'
+          echo "teardown-pr-environment: 'helm uninstall' completed successfully."
+        else
+          RESULT='false'
+          EXIT_CODE=$?
+          echo "ERROR: teardown-pr-environment: 'helm uninstall' did not complete successfully, exit code '${EXIT_CODE}'. Note that this can be expected (e.g. PRs from renovate-bot)."
+        fi
+        echo "::set-output name=result::${RESULT}"
 
     - shell: bash
+      id: kubectl-delete-namespace
       run: |
         # Remove namespace
 
-        kubectl delete namespace ${{ fromJSON(inputs.dsb-build-envs).pr-deploy-k8s-namespace }}
+        if kubectl delete namespace ${{ fromJSON(inputs.dsb-build-envs).pr-deploy-k8s-namespace }}; then
+          RESULT='true'
+          echo "teardown-pr-environment: 'kubectl delete namespace' completed successfully."
+        else
+          RESULT='false'
+          EXIT_CODE=$?
+          echo "ERROR: teardown-pr-environment: 'kubectl delete namespace' did not complete successfully, exit code '${EXIT_CODE}'. Note that this can be expected (e.g. PRs from renovate-bot)."
+        fi
+        echo "::set-output name=result::${RESULT}"
+
+    - shell: bash
+      run: |
+        # Log and evaluate result
+
+        echo "teardown-pr-environment: result: 'helm-uninstall': '${{ steps.helm-uninstall.outputs.result }}'"
+        echo "teardown-pr-environment: result: 'kubectl delete namespace': '${{ steps.kubectl-delete-namespace.outputs.result }}'"
+
+        if [ ! '${{ steps.helm-uninstall.outputs.result }}' == 'true' ] && [ ! '${{ steps.kubectl-delete-namespace.outputs.result }}' == 'true' ]; then
+          echo "ERROR: teardown-pr-environment: failing action since both teardown operations failed!"
+          exit 1
+        elif [ ! '${{ steps.helm-uninstall.outputs.result }}' == 'true' ]; then
+          echo "ERROR: teardown-pr-environment: failing action since helm uninstall operation failed!"
+          exit 1
+        elif [ ! '${{ steps.kubectl-delete-namespace.outputs.result }}' == 'true' ]; then
+          echo "ERROR: teardown-pr-environment: failing action since delete namespace operation failed!"
+          exit 1
+        else
+          echo "teardown-pr-environment: teardown completed successfully."
+        fi
